[package]
name = "rename-ext"
version = "0.1.0"
authors = ["Indiana Kernick <indiana.kernick@gmail.com>"]
description = "Extensions to file renaming that expose capabilities of the platform"
edition = "2021"

[dev-dependencies]
tempfile = "3"
